# This is the kubernetes file for the customer-service
# In the service section, as we want to keep this service accessible only inside the kubernetes cluster
# we have the option of using the NodePort, or ClusterIP. Remember that if you use LoadBalancer in a eks cluster
# a load balancer will be created in AWS, pointing to the node instances of the cluster, which means it will be externally reachable.

kind: Service
apiVersion: v1
metadata:
  name: customer-service
spec:
  selector:
    app: customer-service
  type: NodePort
  ports:
    - port: 80
      targetPort: 9002
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-service
  labels:
    app: customer-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer-service
  template:
    metadata:
      labels:
        app: customer-service
    spec:
      containers:
        - name: customer-service
          image: felipemeriga1/customer-service:latest
          ports:
            - containerPort: 9002